//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQuanLyDangVien.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectQuanLyDangVien.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string SkinBlack {
            get {
                return ResourceManager.GetString("SkinBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string SkinBlue {
            get {
                return ResourceManager.GetString("SkinBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint.
        /// </summary>
        internal static string SkinBlueprint {
            get {
                return ResourceManager.GetString("SkinBlueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caramel.
        /// </summary>
        internal static string SkinCaramel {
            get {
                return ResourceManager.GetString("SkinCaramel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        internal static string SkinCoffee {
            get {
                return ResourceManager.GetString("SkinCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkroom.
        /// </summary>
        internal static string SkinDarkroom {
            get {
                return ResourceManager.GetString("SkinDarkroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Side.
        /// </summary>
        internal static string SkinDarkSide {
            get {
                return ResourceManager.GetString("SkinDarkSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevExpress Dark Style.
        /// </summary>
        internal static string SkinDevExpressDarkStyle {
            get {
                return ResourceManager.GetString("SkinDevExpressDarkStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevExpress Style.
        /// </summary>
        internal static string SkinDevExpressStyle {
            get {
                return ResourceManager.GetString("SkinDevExpressStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foggy.
        /// </summary>
        internal static string SkinFoggy {
            get {
                return ResourceManager.GetString("SkinFoggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Oceans.
        /// </summary>
        internal static string SkinGlassOceans {
            get {
                return ResourceManager.GetString("SkinGlassOceans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string SkinHighContrast {
            get {
                return ResourceManager.GetString("SkinHighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iMaginary.
        /// </summary>
        internal static string SkiniMaginary {
            get {
                return ResourceManager.GetString("SkiniMaginary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lilian.
        /// </summary>
        internal static string SkinLilian {
            get {
                return ResourceManager.GetString("SkinLilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Sky.
        /// </summary>
        internal static string SkinLiquidSky {
            get {
                return ResourceManager.GetString("SkinLiquidSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London Liquid Sky.
        /// </summary>
        internal static string SkinLondonLiquidSky {
            get {
                return ResourceManager.GetString("SkinLondonLiquidSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to McSkin.
        /// </summary>
        internal static string SkinMcSkin {
            get {
                return ResourceManager.GetString("SkinMcSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metropolis.
        /// </summary>
        internal static string SkinMetropolis {
            get {
                return ResourceManager.GetString("SkinMetropolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metropolis Dark.
        /// </summary>
        internal static string SkinMetropolisDark {
            get {
                return ResourceManager.GetString("SkinMetropolisDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Twins.
        /// </summary>
        internal static string SkinMoneyTwins {
            get {
                return ResourceManager.GetString("SkinMoneyTwins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Black.
        /// </summary>
        internal static string SkinOffice2007Black {
            get {
                return ResourceManager.GetString("SkinOffice2007Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Blue.
        /// </summary>
        internal static string SkinOffice2007Blue {
            get {
                return ResourceManager.GetString("SkinOffice2007Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Green.
        /// </summary>
        internal static string SkinOffice2007Green {
            get {
                return ResourceManager.GetString("SkinOffice2007Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Pink.
        /// </summary>
        internal static string SkinOffice2007Pink {
            get {
                return ResourceManager.GetString("SkinOffice2007Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Silver.
        /// </summary>
        internal static string SkinOffice2007Silver {
            get {
                return ResourceManager.GetString("SkinOffice2007Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010 Black.
        /// </summary>
        internal static string SkinOffice2010Black {
            get {
                return ResourceManager.GetString("SkinOffice2010Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010 Blue.
        /// </summary>
        internal static string SkinOffice2010Blue {
            get {
                return ResourceManager.GetString("SkinOffice2010Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010 Silver.
        /// </summary>
        internal static string SkinOffice2010Silver {
            get {
                return ResourceManager.GetString("SkinOffice2010Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2013.
        /// </summary>
        internal static string SkinOffice2013 {
            get {
                return ResourceManager.GetString("SkinOffice2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2013 Dark Gray.
        /// </summary>
        internal static string SkinOffice2013DarkGray {
            get {
                return ResourceManager.GetString("SkinOffice2013DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2013 Light Gray.
        /// </summary>
        internal static string SkinOffice2013LightGray {
            get {
                return ResourceManager.GetString("SkinOffice2013LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2016 Colorful.
        /// </summary>
        internal static string SkinOffice2016Colorful {
            get {
                return ResourceManager.GetString("SkinOffice2016Colorful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2016 Dark.
        /// </summary>
        internal static string SkinOffice2016Dark {
            get {
                return ResourceManager.GetString("SkinOffice2016Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        internal static string SkinPumpkin {
            get {
                return ResourceManager.GetString("SkinPumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string SkinSeven {
            get {
                return ResourceManager.GetString("SkinSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Classic.
        /// </summary>
        internal static string SkinSevenClassic {
            get {
                return ResourceManager.GetString("SkinSevenClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp.
        /// </summary>
        internal static string SkinSharp {
            get {
                return ResourceManager.GetString("SkinSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp Plus.
        /// </summary>
        internal static string SkinSharpPlus {
            get {
                return ResourceManager.GetString("SkinSharpPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Springtime.
        /// </summary>
        internal static string SkinSpringtime {
            get {
                return ResourceManager.GetString("SkinSpringtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stardust.
        /// </summary>
        internal static string SkinStardust {
            get {
                return ResourceManager.GetString("SkinStardust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer 2008.
        /// </summary>
        internal static string SkinSummer2008 {
            get {
                return ResourceManager.GetString("SkinSummer2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Asphalt World.
        /// </summary>
        internal static string SkinTheAsphaltWorld {
            get {
                return ResourceManager.GetString("SkinTheAsphaltWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valentine.
        /// </summary>
        internal static string SkinValentine {
            get {
                return ResourceManager.GetString("SkinValentine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2013 Blue.
        /// </summary>
        internal static string SkinVisualStudio2013Blue {
            get {
                return ResourceManager.GetString("SkinVisualStudio2013Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2013 Dark.
        /// </summary>
        internal static string SkinVisualStudio2013Dark {
            get {
                return ResourceManager.GetString("SkinVisualStudio2013Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2013 Light.
        /// </summary>
        internal static string SkinVisualStudio2013Light {
            get {
                return ResourceManager.GetString("SkinVisualStudio2013Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2010.
        /// </summary>
        internal static string SkinVS2010 {
            get {
                return ResourceManager.GetString("SkinVS2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiteprint.
        /// </summary>
        internal static string SkinWhiteprint {
            get {
                return ResourceManager.GetString("SkinWhiteprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xmas 2008 Blue.
        /// </summary>
        internal static string SkinXmas2008Blue {
            get {
                return ResourceManager.GetString("SkinXmas2008Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trnsl.1.1.20160520T082638Z.56602c00aaed03c7.1e7672334cc02f53eff2429421dd3167e1950278.
        /// </summary>
        internal static string YandexAPIKey {
            get {
                return ResourceManager.GetString("YandexAPIKey", resourceCulture);
            }
        }
    }
}
